//
//  GitHubRepositorySearchServiceTests.swift
//  LetsTest-GitHubSearchTests
//
//  Created by 윤중현 on 2022/11/22.
//

import XCTest
@testable import LetsTest_GitHubSearch

final class GitHubRepositorySearchServiceTests: XCTestCase {

    /**
     * 전달 받은 키워드로 GitHub 에 요청하여 응답 중 repositories 를 추출하여 completion 을 호출합니다.
     */
    func testSearchRepositories() {
        // given
        // when
        // then
    }

}

private let jsonResponseOfReactorKit = """
{
  "total_count": 182,
  "incomplete_results": false,
  "items": [
    {
      "id": 78230922,
      "node_id": "MDEwOlJlcG9zaXRvcnk3ODIzMDkyMg==",
      "name": "ReactorKit",
      "full_name": "ReactorKit/ReactorKit",
      "private": false,
      "owner": {
        "login": "ReactorKit",
        "id": 25218880,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjI1MjE4ODgw",
        "avatar_url": "https://avatars.githubusercontent.com/u/25218880?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ReactorKit",
        "html_url": "https://github.com/ReactorKit",
        "followers_url": "https://api.github.com/users/ReactorKit/followers",
        "following_url": "https://api.github.com/users/ReactorKit/following{/other_user}",
        "gists_url": "https://api.github.com/users/ReactorKit/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ReactorKit/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ReactorKit/subscriptions",
        "organizations_url": "https://api.github.com/users/ReactorKit/orgs",
        "repos_url": "https://api.github.com/users/ReactorKit/repos",
        "events_url": "https://api.github.com/users/ReactorKit/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ReactorKit/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/ReactorKit/ReactorKit",
      "description": "A library for reactive and unidirectional Swift applications",
      "fork": false,
      "url": "https://api.github.com/repos/ReactorKit/ReactorKit",
      "forks_url": "https://api.github.com/repos/ReactorKit/ReactorKit/forks",
      "keys_url": "https://api.github.com/repos/ReactorKit/ReactorKit/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/ReactorKit/ReactorKit/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/ReactorKit/ReactorKit/teams",
      "hooks_url": "https://api.github.com/repos/ReactorKit/ReactorKit/hooks",
      "issue_events_url": "https://api.github.com/repos/ReactorKit/ReactorKit/issues/events{/number}",
      "events_url": "https://api.github.com/repos/ReactorKit/ReactorKit/events",
      "assignees_url": "https://api.github.com/repos/ReactorKit/ReactorKit/assignees{/user}",
      "branches_url": "https://api.github.com/repos/ReactorKit/ReactorKit/branches{/branch}",
      "tags_url": "https://api.github.com/repos/ReactorKit/ReactorKit/tags",
      "blobs_url": "https://api.github.com/repos/ReactorKit/ReactorKit/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/ReactorKit/ReactorKit/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/ReactorKit/ReactorKit/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/ReactorKit/ReactorKit/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/ReactorKit/ReactorKit/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/ReactorKit/ReactorKit/languages",
      "stargazers_url": "https://api.github.com/repos/ReactorKit/ReactorKit/stargazers",
      "contributors_url": "https://api.github.com/repos/ReactorKit/ReactorKit/contributors",
      "subscribers_url": "https://api.github.com/repos/ReactorKit/ReactorKit/subscribers",
      "subscription_url": "https://api.github.com/repos/ReactorKit/ReactorKit/subscription",
      "commits_url": "https://api.github.com/repos/ReactorKit/ReactorKit/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/ReactorKit/ReactorKit/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/ReactorKit/ReactorKit/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/ReactorKit/ReactorKit/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/ReactorKit/ReactorKit/contents/{+path}",
      "compare_url": "https://api.github.com/repos/ReactorKit/ReactorKit/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/ReactorKit/ReactorKit/merges",
      "archive_url": "https://api.github.com/repos/ReactorKit/ReactorKit/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/ReactorKit/ReactorKit/downloads",
      "issues_url": "https://api.github.com/repos/ReactorKit/ReactorKit/issues{/number}",
      "pulls_url": "https://api.github.com/repos/ReactorKit/ReactorKit/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/ReactorKit/ReactorKit/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/ReactorKit/ReactorKit/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/ReactorKit/ReactorKit/labels{/name}",
      "releases_url": "https://api.github.com/repos/ReactorKit/ReactorKit/releases{/id}",
      "deployments_url": "https://api.github.com/repos/ReactorKit/ReactorKit/deployments",
      "created_at": "2017-01-06T18:59:12Z",
      "updated_at": "2022-11-12T14:43:41Z",
      "pushed_at": "2022-08-03T12:07:22Z",
      "git_url": "git://github.com/ReactorKit/ReactorKit.git",
      "ssh_url": "git@github.com:ReactorKit/ReactorKit.git",
      "clone_url": "https://github.com/ReactorKit/ReactorKit.git",
      "svn_url": "https://github.com/ReactorKit/ReactorKit",
      "homepage": "http://reactorkit.io",
      "size": 623,
      "stargazers_count": 2461,
      "watchers_count": 2461,
      "language": "Swift",
      "has_issues": true,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 250,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 34,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "architecture",
        "reactive",
        "reactorkit",
        "rxswift",
        "swift",
        "unidirectional"
      ],
      "visibility": "public",
      "forks": 250,
      "open_issues": 34,
      "watchers": 2461,
      "default_branch": "master",
      "score": 1.0
    },
    {
      "id": 62412616,
      "node_id": "MDEwOlJlcG9zaXRvcnk2MjQxMjYxNg==",
      "name": "RxTodo",
      "full_name": "devxoul/RxTodo",
      "private": false,
      "owner": {
        "login": "devxoul",
        "id": 931655,
        "node_id": "MDQ6VXNlcjkzMTY1NQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/931655?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/devxoul",
        "html_url": "https://github.com/devxoul",
        "followers_url": "https://api.github.com/users/devxoul/followers",
        "following_url": "https://api.github.com/users/devxoul/following{/other_user}",
        "gists_url": "https://api.github.com/users/devxoul/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/devxoul/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/devxoul/subscriptions",
        "organizations_url": "https://api.github.com/users/devxoul/orgs",
        "repos_url": "https://api.github.com/users/devxoul/repos",
        "events_url": "https://api.github.com/users/devxoul/events{/privacy}",
        "received_events_url": "https://api.github.com/users/devxoul/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/devxoul/RxTodo",
      "description": "iOS Todo Application using RxSwift and ReactorKit",
      "fork": false,
      "url": "https://api.github.com/repos/devxoul/RxTodo",
      "forks_url": "https://api.github.com/repos/devxoul/RxTodo/forks",
      "keys_url": "https://api.github.com/repos/devxoul/RxTodo/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/devxoul/RxTodo/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/devxoul/RxTodo/teams",
      "hooks_url": "https://api.github.com/repos/devxoul/RxTodo/hooks",
      "issue_events_url": "https://api.github.com/repos/devxoul/RxTodo/issues/events{/number}",
      "events_url": "https://api.github.com/repos/devxoul/RxTodo/events",
      "assignees_url": "https://api.github.com/repos/devxoul/RxTodo/assignees{/user}",
      "branches_url": "https://api.github.com/repos/devxoul/RxTodo/branches{/branch}",
      "tags_url": "https://api.github.com/repos/devxoul/RxTodo/tags",
      "blobs_url": "https://api.github.com/repos/devxoul/RxTodo/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/devxoul/RxTodo/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/devxoul/RxTodo/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/devxoul/RxTodo/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/devxoul/RxTodo/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/devxoul/RxTodo/languages",
      "stargazers_url": "https://api.github.com/repos/devxoul/RxTodo/stargazers",
      "contributors_url": "https://api.github.com/repos/devxoul/RxTodo/contributors",
      "subscribers_url": "https://api.github.com/repos/devxoul/RxTodo/subscribers",
      "subscription_url": "https://api.github.com/repos/devxoul/RxTodo/subscription",
      "commits_url": "https://api.github.com/repos/devxoul/RxTodo/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/devxoul/RxTodo/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/devxoul/RxTodo/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/devxoul/RxTodo/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/devxoul/RxTodo/contents/{+path}",
      "compare_url": "https://api.github.com/repos/devxoul/RxTodo/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/devxoul/RxTodo/merges",
      "archive_url": "https://api.github.com/repos/devxoul/RxTodo/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/devxoul/RxTodo/downloads",
      "issues_url": "https://api.github.com/repos/devxoul/RxTodo/issues{/number}",
      "pulls_url": "https://api.github.com/repos/devxoul/RxTodo/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/devxoul/RxTodo/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/devxoul/RxTodo/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/devxoul/RxTodo/labels{/name}",
      "releases_url": "https://api.github.com/repos/devxoul/RxTodo/releases{/id}",
      "deployments_url": "https://api.github.com/repos/devxoul/RxTodo/deployments",
      "created_at": "2016-07-01T18:31:50Z",
      "updated_at": "2022-11-08T20:18:16Z",
      "pushed_at": "2022-10-05T19:20:12Z",
      "git_url": "git://github.com/devxoul/RxTodo.git",
      "ssh_url": "git@github.com:devxoul/RxTodo.git",
      "clone_url": "https://github.com/devxoul/RxTodo.git",
      "svn_url": "https://github.com/devxoul/RxTodo",
      "homepage": "",
      "size": 190,
      "stargazers_count": 1275,
      "watchers_count": 1275,
      "language": "Swift",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 174,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 9,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "ios",
        "reactorkit",
        "rxswift",
        "swift",
        "todo"
      ],
      "visibility": "public",
      "forks": 174,
      "open_issues": 9,
      "watchers": 1275,
      "default_branch": "master",
      "score": 1.0
    }
  ]
}
"""
